# Define variables and parameters
- template: Variables/global.yml
- template: Parameters/global.yml

# Define stages
stages:

# Validate
- template: Stages/validate.yml

# Plan
- template: Stages/plan.yml

# Apply
- template: Stages/apply.yml

# RePlan
- template: Stages/replan.yml

# ReApply
- template: Stages/reapply.yml