# Trigger builds on commits and merges to branch
trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
      - EdgeServices/

# Do not trigger builds on PRs
pr: none

# Execute on a schedule (measure drift from desired state)
schedules:
- cron: "0 */24 * * *"
  displayName: Run daily
  branches:
    include:
    - main
  always: true

extends:
  template: ../../Shared/azure-pipelines.yml