variables:
- group: 'terraform-backend'
- group: 'terraform-system'
stages:
- stage: Validate
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: Import
    continueOnError: false
    steps:
    - task: TerraformInstaller@0
      displayName: 'Terraform Install'
      inputs:
        terraformVersion: '$(terraformVersion)'
    - task: TerraformCLI@0
      displayName: 'Terraform Initialise'
      inputs:
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Compute/DirectoryServices/'
        backendType: 'azurerm'
        backendServiceArm: '$(backendServiceArm)'
        ensureBackend: true
        backendAzureRmResourceGroupName: '$(backendAzureRmResourceGroupName)'
        backendAzureRmResourceGroupLocation: '$(backendAzureRmResourceGroupLocation)'
        backendAzureRmStorageAccountName: '$(backendAzureRmStorageAccountName)'
        backendAzureRmContainerName: '$(backendAzureRmContainerName)'
        backendAzureRmKey: '$(backendAzureRmKey)'
        allowTelemetryCollection: false
    - task: TerraformCLI@0
      displayName: 'Terraform Validate'
      inputs:
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Compute/DirectoryServices/'
        allowTelemetryCollection: false
- stage: Plan
  pool:
    vmImage: 'ubuntu-latest'
  dependsOn: Validate
  jobs:
  - job: Evaluate
    continueOnError: false
    steps:
    - task: TerraformInstaller@0
      displayName: 'Terraform Install'
      inputs:
        terraformVersion: '$(terraformVersion)'
    - task: TerraformCLI@0
      displayName: 'Terraform Initialise'
      inputs:
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Compute/DirectoryServices/'
        backendType: 'azurerm'
        backendServiceArm: '$(backendServiceArm)'
        ensureBackend: true
        backendAzureRmResourceGroupName: '$(backendAzureRmResourceGroupName)'
        backendAzureRmResourceGroupLocation: '$(backendAzureRmResourceGroupLocation)'
        backendAzureRmStorageAccountName: '$(backendAzureRmStorageAccountName)'
        backendAzureRmContainerName: '$(backendAzureRmContainerName)'
        backendAzureRmKey: '$(backendAzureRmKey)'
        allowTelemetryCollection: false
    - task: PowerShell@2
      displayName: 'Create artifact directory'
      inputs:
        targetType: 'inline'
        script: |

          # Create directory for artifact, if it does not exist
          $TestPath = Test-Path $(Pipeline.Workspace)/Output -PathType Container
          if (!$TestPath){
              New-Item -Path $(Pipeline.Workspace)/Output -ItemType Directory | Out-Null
          }
        pwsh: true
        workingDirectory: '$(System.ArtifactsDirectory)'
    - task: TerraformCLI@0
      displayName: 'Terraform Plan'
      inputs:
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Compute/DirectoryServices/'
        environmentServiceName: '$(backendServiceArm)'
        publishPlanResults: 'terraform.tfplan'
        commandOptions: '-out=$(Pipeline.Workspace)/Output/terraform.tfplan -detailed-exitcode'
    - task: PowerShell@2
      displayName: 'Publish output variable'
      name: 'Variable'
      inputs:
        targetType: 'inline'
        script: |

            # Set ShouldRun variable to true, for apply stage
            if ($ENV:TERRAFORM_PLAN_HAS_CHANGES){
              echo "##vso[task.setvariable variable=ShouldRun;isOutput=true]true"
            }

        pwsh: true
        workingDirectory: '$(System.ArtifactsDirectory)'
    - task: PublishPipelineArtifact@1
      displayName: 'Publish plan artifact'
      inputs:
        targetPath: '$(Pipeline.Workspace)/Output'
        artifact: 'Evaluate'
        publishLocation: 'pipeline'
- stage: Apply
  pool:
    vmImage: 'ubuntu-latest'
  dependsOn: Plan
  condition: and(succeeded(), eq(dependencies.Plan.outputs['Evaluate.Variable.ShouldRun'], 'true'))
  jobs:
  - deployment: Deploy
    continueOnError: false
    environment: $(Environment)
    strategy:
     runOnce:
       deploy:
        steps:
          - checkout: self
          - task: TerraformInstaller@0
            displayName: 'Terraform Install'
            inputs:
              terraformVersion: '$(terraformVersion)'
          - task: TerraformCLI@0
            displayName: 'Terraform Initialise'
            inputs:
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/Compute/DirectoryServices/'
              backendType: 'azurerm'
              backendServiceArm: '$(backendServiceArm)'
              ensureBackend: true
              backendAzureRmResourceGroupName: '$(backendAzureRmResourceGroupName)'
              backendAzureRmResourceGroupLocation: '$(backendAzureRmResourceGroupLocation)'
              backendAzureRmStorageAccountName: '$(backendAzureRmStorageAccountName)'
              backendAzureRmContainerName: '$(backendAzureRmContainerName)'
              backendAzureRmKey: '$(backendAzureRmKey)'
              allowTelemetryCollection: false
          - task: TerraformCLI@0
            displayName: 'Terraform Apply'
            inputs:
              command: 'apply'
              workingDirectory: '$(System.DefaultWorkingDirectory)/Compute/DirectoryServices/'
              environmentServiceName: '$(backendServiceArm)'
              commandOptions: '$(Pipeline.Workspace)/Evaluate/terraform.tfplan.json'