# Trigger builds on commits and merges to branch
trigger:
  batch: true
  branches:
    include:
    - develop
  paths:
    include:
      - DirectoryServices/

# Do not trigger builds on PRs
pr: none

# Trigger as a result of the Cloud Platform pipeline
resources:
  pipelines:
  - pipeline: CloudPlatform
    source: 'SVC-CP;ENV-D; Cloud Platform'
    trigger: 
      branches:
      - develop

extends:
  template: ../../Shared/azure-pipelines.yml