# Do not trigger builds on commits and merges to branch
trigger: none

# Do not trigger builds on PRs
pr: none

# Execute on a schedule
schedules:
- cron: "0 */24 * * *"
  displayName: Run daily
  branches:
    include:
    - develop
  always: true
stages:
  - stage: Pipelines
    displayName: 'Trigger all pipelines'
    jobs:
    - job: Trigger
      steps:
      # required to cause pipeline triggering downstream
      - task: CopyFiles@2
        inputs:
          contents: $(System.DefaultWorkingDirectory)/**/*.yml
          targetFolder: $(Build.ArtifactStagingDirectory)
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: $(Build.ArtifactStagingDirectory)
          artifactName: dummy-$(Build.BuildId)