# Trigger builds on commits and merges to branch
trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
      - ManagementServices/

# Do not trigger builds on PRs
pr: none

# Execute on a schedule
schedules:
- cron: "0 */24 * * *"
  displayName: Run daily
  branches:
    include:
    - main
  always: true

extends:
  template: ../../Shared/validate.yml