stages:

- stage: Apply
  pool:
    vmImage: 'ubuntu-latest'
  dependsOn: Plan
  condition: and(succeeded(), eq(dependencies.Plan.outputs['Evaluate.Variable.ShouldRun'], 'true'))
  jobs:
  
  - deployment: Deploy
    environment: $(Environment)
    strategy:
     runOnce:
       deploy:
        steps:

          # Checkout repo
          - checkout: self
    
          # Terraform bootstrap
          - template: ../Steps/bootstrap.yml

          # Select workspace
          - template: ../Steps/workspace.yml
          
          # Terraform Apply
          - template: ../Steps/terraform.yml
            parameters:
              name: 'Apply'
              displayName: 'Terraform Apply'
              condition: succeeded()
              command: 'apply'
              commandOptions: '$(Pipeline.Workspace)/Evaluate/apply_terraform.tfplan'