stages:
- stage: Apply
  pool:
    vmImage: 'ubuntu-latest'
  dependsOn: Plan
  condition: and(succeeded(), eq(dependencies.Plan.outputs['Evaluate.Variable.ShouldRun'], 'true'))
  jobs:
  - deployment: Deploy
    continueOnError: true
    environment: $(Environment)
    strategy:
     runOnce:
       deploy:
        steps:

          # Checkout repo
          - checkout: self
    
          # Terraform Install and initialise
          - template: ../Steps/bootstrap.yml

          # Terraform Apply
          - task: TerraformCLI@0
            displayName: 'Terraform Apply'
            inputs:
              command: 'apply'
              workingDirectory: '$(System.DefaultWorkingDirectory)/$(Service)/'
              environmentServiceName: '$(backendServiceArm)'
              commandOptions: '$(Pipeline.Workspace)/Evaluate/apply_terraform.tfplan'