stages:

- stage: AutoReApply
  pool:
    vmImage: 'ubuntu-latest'
  dependsOn: Apply
  condition: Failed()
  jobs:
  
  - deployment: AutoReDeploy
    environment: '$(Environment-ReApply)'
    strategy:
     runOnce:
       deploy:
        steps:

          # Checkout repo
          - checkout: self
    
          # Terraform bootstrap
          - template: ../Steps/bootstrap.yml
         
          # Terraform Apply
          - template: ../Steps/terraform.yml
            parameters:
              name: 'ReApply'
              displayName: 'Terraform Apply'
              command: 'apply'