stages:

- stage: AutoApply
  pool:
    vmImage: 'ubuntu-latest'
  dependsOn: Apply
  condition: Failed('Apply')
  jobs:
  
  - deployment: AutoDeploy
    environment: '$(Environment-AutoApply)'
    strategy:
     runOnce:
       deploy:
        steps:

          # Checkout repo
          - checkout: self
    
          # Terraform bootstrap
          - template: ../Steps/bootstrap.yml
          
          # Terraform workspace select
          - template: ../Steps/workspace_select.yml

          # Terraform Apply
          - template: ../Steps/terraform.yml
            parameters:
              name: 'AutoApply'
              displayName: 'Terraform Apply'
              command: 'apply'