stages:
- stage: Plan
  pool:
    vmImage: 'ubuntu-latest'
  dependsOn: Validate
  jobs:
  - job: Evaluate
    continueOnError: false
    steps:
    
    # Terraform Install and initialise
    - template: ../Steps/bootstrap.yml

    # Create artifact directory
    - template: ../Steps/mkdir.yml
    
    # Terraform Plan
    - template: ../Steps/terraform.yml
      parameters:
        displayName: 'Terraform Plan'
        command: 'plan'
        publishPlanResults: 'apply_terraform.tfplan'
        commandOptions: '-out=$(Pipeline.Workspace)/Output/apply_terraform.tfplan -detailed-exitcode'
    
    # Set pipeline output variable if there are changes
    - template: ../Steps/variable.yml
    
    # Publish artifact
    - template: ../Steps/artifact.yml
      parameters:
        artifact: 'Evaluate'