stages:
- stage: ReApply
  pool:
    vmImage: 'ubuntu-latest'
  dependsOn: RePlan
  condition: and(succeeded('RePlan'), eq(dependencies.RePlan.outputs['ReEvaluate.Variable.ShouldRun'], 'true'))
  jobs:
  - deployment: ReDeploy
    continueOnError: true
    environment: '$(Environment-ReApply)'
    strategy:
     runOnce:
       deploy:
        steps:

          # Checkout repo
          - checkout: self
    
          # Terraform Install and initialise
          - template: ../Steps/bootstrap.yml

          # Terraform Apply
          - task: TerraformCLI@0
            displayName: 'Terraform Apply'
            inputs:
              command: 'apply'
              workingDirectory: '$(System.DefaultWorkingDirectory)/$(Service)/'
              environmentServiceName: '$(backendServiceArm)'
              commandOptions: '$(Pipeline.Workspace)/ReEvaluate/reapply_terraform.tfplan'