stages:

- stage: ReApply
  pool:
    vmImage: 'ubuntu-latest'
  dependsOn: RePlan
  condition: and(succeeded('RePlan'), eq(dependencies.RePlan.outputs['ReEvaluate.Variable.ShouldRun'], 'true'))
  jobs:
  
  - deployment: ReDeploy
    continueOnError: true
    environment: '$(Environment)'
    strategy:
     runOnce:
       deploy:
        steps:

          # Checkout repo
          - checkout: self
    
          # Terraform bootstrap
          - template: ../Steps/bootstrap.yml
         
          # Terraform Apply
          - template: ../Steps/terraform.yml
            parameters:
              name: 'ReApply'
              displayName: 'Terraform Apply'
              command: 'apply'
              commandOptions: '$(Pipeline.Workspace)/ReEvaluate/reapply_terraform.tfplan'