stages:
- stage: RePlan
  pool:
    vmImage: 'ubuntu-latest'
  dependsOn: Apply
  condition: and(succeeded('Plan'), eq(dependencies.Plan.outputs['Evaluate.Variable.ShouldRun'], 'true'))
  jobs:
  
  # Delay job
  - template: ../Jobs/delay.yml
  
  # Re-evaluate plan
  - job: ReEvaluate
    dependsOn: Delay
    continueOnError: false
    steps:
    
    # Terraform Install and initialise
    - template: ../Steps/bootstrap.yml

    # Create artifact directory
    - template: ../Steps/mkdir.yml
       
    # Terraform Plan
    - template: ../Steps/terraform.yml
      parameters:
        name: 'RePlan'
        displayName: 'Terraform Plan'
        command: 'plan'
        publishPlanResults: 'reapply_terraform.tfplan'
        commandOptions: '-out=$(Pipeline.Workspace)/Output/reapply_terraform.tfplan -detailed-exitcode'
    
    # Set pipeline output variable if there are changes
    - template: ../Steps/variable.yml
    
    # Publish artifact
    - template: ../Steps/artifact.yml
      parameters:
        artifact: 'ReEvaluate'