stages:
- stage: Validate
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  
  # Terraform Install and initialise
  - template: ../Jobs/bootstrap.yml
  
  # Terraform Validate
  - template: ../Jobs/validate.yml