stages:

- stage: Validate
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  
  - job: Import
    continueOnError: false
    steps:
    
    # Terraform bootstrap
    - template: ../Steps/bootstrap.yml

    # Create workspace (if does not exist)
    - task: TerraformCLI@0
      condition: Failed()
      displayName: 'Terraform Workspace new'
      inputs:
        workingDirectory: '$(System.DefaultWorkingDirectory)/$(Service)/'
        command: 'workspace'
        workspaceSubCommand: 'new'
        workspaceName: $(Environment)

    # Terraform validate
    - task: TerraformCLI@0
      condition: succeeded('Initialise')
      name: 'Validate'
      displayName: 'Terraform Validate'
      inputs:
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/$(Service)/'
        environmentServiceName: '$(backendServiceArm)'