stages:
- stage: Validate
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: Import
    continueOnError: false
    steps:
    
    # Terraform Install and initialise
    - template: ../Steps/bootstrap.yml
    
    # Terraform Validate
    - template: ../Steps/validate.yml