stages:

- stage: Validate
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  
  - job: Import
    continueOnError: false
    steps:
    
    # Terraform bootstrap
    - template: ../Steps/bootstrap.yml
    
    # Terraform validate
    - template: ../Steps/terraform.yml
      condition: Succeeded()
      parameters:
        name: 'Validate'
        displayName: 'Terraform Validate'
        command: 'validate'
