stages:

- stage: Validate
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  
  - job: Bootstrap
    continueOnError: false
    steps:
    
    # Terraform bootstrap
    - template: ../Steps/bootstrap.yml

    # Terraform Validate
    - template: ../Steps/terraform.yml
      parameters:
        name: 'Validate'
        displayName: 'Terraform Validate'
        command: 'validate'

    # Select workspace (if exists)
    - task: TerraformCLI@0
      name: 'select'
      continueOnError: true
      displayName: 'Terraform Workspace select'
      inputs:
        workingDirectory: '$(System.DefaultWorkingDirectory)/$(Service)/'
        command: 'workspace'
        workspaceSubCommand: 'select'
        workspaceName: $(Environment)

  - job: Workspace
    continueOnError: false
    steps:

    # Create workspace (if does not exist)
    - task: TerraformCLI@0
      condition: eq(dependencies.Bootstrap.result,'SucceededWithIssues')
      displayName: 'Terraform Workspace new'
      inputs:
        workingDirectory: '$(System.DefaultWorkingDirectory)/$(Service)/'
        command: 'workspace'
        workspaceSubCommand: 'new'
        workspaceName: $(Environment)