stages:
- stage: Validate
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: Import
    continueOnError: false
    steps:
    
    # Terraform Install and initialise
    - template: ../Steps/bootstrap.yml
    
    # Terraform validate
    - task: TerraformCLI@0
      displayName: 'Terraform Validate'
      inputs:
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/$(Service)/'