stages:
- stage: Validate
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: Import
    continueOnError: false
    steps:
    
    # Terraform Install and initialise
    - template: ../Steps/bootstrap.yml
    
    # Terraform validate
    - template: ../Steps/terraform.yml
      parameters:
        Name: Validate
        displayName: 'Terraform Validate'
        command: 'validate'
